// Builds src/styles/motifs.css: the doodle pattern each colour theme draws
// behind pages and inside banners (suns for Sunshine, waves and fish for
// Ocean, and so on). Run with `node scripts/build-motifs.mjs` after editing.
import { writeFileSync } from "node:fs";

// Doodles drawn on a 24x24 grid. `f` = filled shapes, `s` = outlined strokes.
const ICONS = {
  sparkle: { f: "M12 1.5c.6 5.6 4.9 9.9 10.5 10.5-5.6.6-9.9 4.9-10.5 10.5-.6-5.6-4.9-9.9-10.5-10.5C7.1 11.4 11.4 7.1 12 1.5Z" },
  dot: { f: "M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8Z" },
  sun: {
    f: "M12 7a5 5 0 1 1 0 10 5 5 0 0 1 0-10Z",
    s: "M12 1.5v2.5M12 20v2.5M1.5 12H4M20 12h2.5M4.6 4.6l1.8 1.8M17.6 17.6l1.8 1.8M4.6 19.4l1.8-1.8M17.6 6.4l1.8-1.8",
  },
  daisy: {
    f: "M12 2.5a3 3 0 0 1 3 3c0 1-.5 2-1.2 2.6 1-.3 2.1-.2 3 .4a3 3 0 1 1-2.6 5.3c.7.6 1.2 1.6 1.1 2.7a3 3 0 1 1-6 0c0-1.1.4-2.1 1.1-2.7a3 3 0 1 1-2.6-5.3c.9-.6 2-.7 3-.4A3.4 3.4 0 0 1 9 5.5a3 3 0 0 1 3-3Z",
  },
  wave: { s: "M1.5 10c2.6-3 5.2-3 7 0s4.4 3 7 0 4.4-3 7 0M1.5 16c2.6-3 5.2-3 7 0s4.4 3 7 0 4.4-3 7 0" },
  bubble: { s: "M12 4a8 8 0 1 1 0 16 8 8 0 0 1 0-16ZM8.5 10a3.5 3.5 0 0 1 3-3" },
  fish: { f: "M2 12c3-5 9-6.5 14-3l5-3.5-1.5 6.5 1.5 6.5-5-3.5c-5 3.5-11 2-14-3Zm7.5-1.6a1.2 1.2 0 1 0 0 2.4 1.2 1.2 0 0 0 0-2.4Z" },
  drop: { f: "M12 2.5s7 7.8 7 12.5a7 7 0 1 1-14 0c0-4.7 7-12.5 7-12.5Z" },
  leaf: { f: "M4 20C4 9.5 10 3.5 21 3.5 21 14 15 20 4 20Z", s: "M4 20 14 10" },
  sprout: { s: "M12 22v-9M12 13c0-4-3-6.5-8-6.5 0 4.5 3 6.5 8 6.5ZM12 11c0-3.8 2.8-6.5 8-6.5 0 4.3-2.8 6.5-8 6.5Z" },
  tree: { f: "M12 1.5 18 10h-3l5 7H4l5-7H6l6-8.5ZM10.5 17h3v5h-3z" },
  acorn: { f: "M5 9.5c0-3 3-5.5 7-5.5s7 2.5 7 5.5H5Zm1 1.5h12c0 6-3 10-6 11-3-1-6-5-6-11ZM11 1h2v3h-2z" },
  heart: { f: "M12 21C4.5 15.4 2.5 11.6 2.5 8.4A4.9 4.9 0 0 1 12 6.6a4.9 4.9 0 0 1 9.5 1.8c0 3.2-2 7-9.5 12.6Z" },
  berry: {
    f: "M12 7c4.6 0 8 1.8 8 4.8 0 4.7-4.5 10.2-8 10.2s-8-5.5-8-10.2C4 8.8 7.4 7 12 7Z",
    s: "M8 7.5 12 4l4 3.5M12 4V1.5",
  },
  rose: { s: "M12 4.5a7.5 7.5 0 1 1-7.5 7.5M12 8a4 4 0 1 1-4 4M12 11a1.2 1.2 0 1 1-1.2 1.2" },
  star: { f: "m12 1.8 3 6.4 7 .9-5.1 4.8 1.3 7-6.2-3.4-6.2 3.4 1.3-7L2 9.1l7-.9 3-6.4Z" },
  planet: { f: "M12 6.5a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11Z", s: "M2.5 15.5c-1.2-2 3.1-5 9.5-7s11-1.9 9.7.4c-.6 1-2.3 2.1-4.6 3.1" },
  moon: { f: "M15 2.5a9.5 9.5 0 1 0 6.5 15.6A8 8 0 0 1 15 2.5Z" },
  rocket: {
    f: "M12 1.5c3.6 2.6 5 6.3 5 10.5l2.5 3.5-1 4-3.3-2.2H8.8L5.5 19.5l-1-4L7 12c0-4.2 1.4-7.9 5-10.5Zm0 7a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z",
    s: "M10.5 20v2.5M13.5 20v2.5",
  },
  // Maths-y bits that show up in every theme, very small.
  plus: { s: "M12 5v14M5 12h14" },
  ring: { s: "M12 5a7 7 0 1 1 0 14 7 7 0 0 1 0-14Z" },
};

// Where each doodle sits on a 200x200 tile: [icon slot, x, y, size, rotation].
// Slots 0-3 are the theme's own doodles; 4 and 5 are the shared small ones.
const LAYOUT = [
  [0, 18, 20, 30, -12],
  [1, 112, 14, 26, 14],
  [4, 168, 58, 12, 0],
  [2, 58, 78, 22, 8],
  [5, 150, 104, 14, 0],
  [3, 92, 128, 30, -18],
  [0, 168, 150, 20, 22],
  [4, 26, 140, 10, 0],
  [1, 22, 176, 18, -6],
  [2, 120, 176, 16, 30],
];

const THEMES = {
  sunshine: { icons: ["sun", "daisy", "sparkle", "star"], light: "#f59e0b", dark: "#fbbf24" },
  ocean: { icons: ["fish", "wave", "bubble", "drop"], light: "#0ea5e9", dark: "#38bdf8" },
  forest: { icons: ["leaf", "sprout", "tree", "acorn"], light: "#16a34a", dark: "#4ade80" },
  berry: { icons: ["heart", "berry", "rose", "sparkle"], light: "#e11d48", dark: "#fb7185" },
  galaxy: { icons: ["star", "planet", "moon", "rocket"], light: "#8b5cf6", dark: "#a78bfa" },
};
const SHARED = ["plus", "ring"];

function drawIcon(name, x, y, size, rot, colour) {
  const icon = ICONS[name];
  const k = size / 24;
  const t = `translate(${x} ${y}) rotate(${rot} ${size / 2} ${size / 2}) scale(${k.toFixed(3)})`;
  let out = `<g transform="${t}">`;
  if (icon.f) out += `<path d="${icon.f}" fill="${colour}"/>`;
  if (icon.s)
    out += `<path d="${icon.s}" fill="none" stroke="${colour}" stroke-width="${(2.2).toFixed(1)}" stroke-linecap="round" stroke-linejoin="round"/>`;
  return out + "</g>";
}

function tile(icons, colour, opacity) {
  const slots = [...icons, ...SHARED];
  const body = LAYOUT.map(([slot, x, y, size, rot]) => drawIcon(slots[slot], x, y, size, rot, colour)).join("");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200"><g opacity="${opacity}">${body}</g></svg>`;
  return `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;
}

// One big doodle on its own, used as a corner decoration.
function single(name, colour) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96">${drawIcon(name, 0, 0, 96, 0, colour)}</svg>`;
  return `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;
}

let css = `/* Generated by scripts/build-motifs.mjs. Edit that file, not this one. */\n`;
for (const [id, t] of Object.entries(THEMES)) {
  const sel = id === "sunshine" ? `:root, [data-theme="sunshine"]` : `[data-theme="${id}"]`;
  const dsel = id === "sunshine" ? `.dark, .dark[data-theme="sunshine"]` : `.dark[data-theme="${id}"]`;
  css += `
${sel} {
  --motif: ${tile(t.icons, t.light, 0.16)};
  --motif-on: ${tile(t.icons, "#ffffff", 0.22)};
  --motif-icon: ${single(t.icons[0], t.light)};
  --motif-icon-2: ${single(t.icons[1], t.light)};
}
${dsel} {
  --motif: ${tile(t.icons, t.dark, 0.09)};
  --motif-on: ${tile(t.icons, "#ffffff", 0.14)};
  --motif-icon: ${single(t.icons[0], t.dark)};
  --motif-icon-2: ${single(t.icons[1], t.dark)};
}
`;
}
writeFileSync(new URL("../src/styles/motifs.css", import.meta.url), css);
console.log("Wrote src/styles/motifs.css");
